apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"httpd-deployment"},"name":"httpd-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"httpd-deployment"}},"template":{"metadata":{"labels":{"app":"httpd-deployment"}},"spec":{"containers":[{"image":"httpd","name":"httpd","ports":[{"containerPort":80,"name":"http-port"}]}]}}}}
  creationTimestamp: "2022-01-06T05:57:52Z"
  generation: 6
  labels:
    app: httpd-deployment
  name: httpd-deployment
  namespace: default
  resourceVersion: "46130"
  uid: 7e836452-426f-42cf-8e57-6ed2db201e1a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpd-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd-deployment
    spec:
      containers:
      - image: carytakeshi/githubimage:172022
        imagePullPolicy: Always
        name: carytakeshi
        ports:
        - containerPort: 80
          name: http-port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-06T05:59:21Z"
    lastUpdateTime: "2022-01-06T05:59:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-06T05:57:52Z"
    lastUpdateTime: "2022-01-07T05:18:45Z"
    message: ReplicaSet "httpd-deployment-5cc7449854" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
