- name: sample playbook
  hosts: target-server
  become: true
  tasks:
    - name: create new directory
      command: kubectl apply -f /var/lib/jenkins/jobs/github-jenkins-dockerhub/workspace/deployment.yaml
